pipeline {
    agent any
tools {maven 'mvn'}

    stages {
        stage('scm') {
            steps {
        git 'https://github.com/kaviyavarma08/WarProject.git'
            }
        }
        stage('build') {
            steps {
               sh "mvn clean"
               sh "mvn install"
}
}
stage('build to images') {
            steps {
               script{
                  sh 'docker build -t jebinjosej/simplewebapp .'
               }
    }
}
stage('push to hub') {
            steps {
               script{
                 withDockerRegistry(credentialsId: 'Docker', url: 'https://index.docker.io/v1/') {
                  sh 'docker push jebinjosej/simplewebapp'
               }
            }
 	}
}
}
}
